name: Build / Beta

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm

            - name: Install dependencies
              run: npm i

            - name: Generate Seed Database
              run: npm run seed

            - name: Build and package
              run: npm run package

            - name: Upload installer
              uses: actions/upload-artifact@v4
              with:
                name: eve-sov-tool-win-installer
                path: dist/*.exe

            - name: Upload portable zip
              uses: actions/upload-artifact@v4
              with:
                name: eve-sov-tool-win-portable
                path: dist/*.zip

            - name: Get current time
              uses: josStorer/get-current-time@v2
              id: current-time
              with:
                format: YYYYMMDD-HH
                utcOffset: "+00:00"
            
            - name: Release
              uses: actions/create-release@v1
              with:
                draft: false
                prerelease: true
                release_name: ${{ steps.current-time.outputs.time }} BETA
                tag_name: BETA
              env:
                GITHUB_TOKEN: ${{ github.token }}
